import { createRouter as createTanStackRouter } from "@tanstack/react-router";
// Generated by the TanStack Start Vite plugin on dev/build (git-ignored).
import { routeTree } from "./routeTree.gen";

export function getRouter() {
  return createTanStackRouter({
    routeTree,
    scrollRestoration: true,
  });
}

declare module "@tanstack/react-router" {
  interface Register {
    router: ReturnType<typeof getRouter>;
  }
}
