import { chmodSync, existsSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { delimiter, join } from "node:path";
import { describe, expect, it } from "vitest";
import { defaultShimDir, findExecutable, installShims, uninstallShims } from "../src/install.js";

function tempDir(name: string): string {
  return mkdtempSync(join(tmpdir(), name));
}

function executable(path: string): void {
  writeFileSync(path, "#!/bin/sh\nexit 0\n", { mode: 0o755 });
  chmodSync(path, 0o755);
}

describe("ficta shims", () => {
  it("installs agent-plugin shims and a managed PATH block", () => {
    const home = tempDir("ficta-home-");
    const realBin = tempDir("ficta-real-bin-");
    executable(join(realBin, "claude"));
    executable(join(realBin, "codex"));
    executable(join(realBin, "pi"));
    const rcPath = join(home, ".zshrc");

    const result = installShims({
      home,
      rcPath,
      pathEnv: realBin,
      nodePath: "/usr/bin/node",
      fictaBin: "/repo/bin/ficta.mjs",
      agents: ["claude", "codex", "pi"],
    });

    expect(result.launcher.status).toBe("installed");
    expect(result.shims.map((s) => s.status)).toEqual(["installed", "installed", "installed"]);
    expect(result.pathUpdated).toBe(true);
    const shimDir = defaultShimDir(home);
    const launcher = readFileSync(join(shimDir, ".ficta-launcher"), "utf8");
    const claudeShim = readFileSync(join(shimDir, "claude"), "utf8");
    expect(launcher).toContain("Generated by ficta");
    expect(launcher).toContain("FICTA_LAUNCHER=1");
    expect(launcher).toContain("/repo/bin/ficta.mjs");
    expect(claudeShim).toContain("Generated by ficta");
    expect(claudeShim).toContain("FICTA_SHIM_AGENT='claude'");
    expect(claudeShim).toContain('exec "$shim_dir/.ficta-launcher" \'claude\' "$@"');
    expect(existsSync(join(shimDir, "ficta"))).toBe(false);
    expect(readFileSync(rcPath, "utf8")).toContain(`export PATH="${shimDir}:$PATH"`);
  });

  it("uses env node in the hidden launcher by default", () => {
    const home = tempDir("ficta-home-");

    installShims({
      home,
      updateShell: false,
      fictaBin: "/repo/bin/ficta.mjs",
      agents: ["pi"],
    });

    const shimDir = defaultShimDir(home);
    const launcher = readFileSync(join(shimDir, ".ficta-launcher"), "utf8");
    const piShim = readFileSync(join(shimDir, "pi"), "utf8");
    expect(launcher).toContain("exec /usr/bin/env node '/repo/bin/ficta.mjs'");
    expect(piShim).not.toContain("/repo/bin/ficta.mjs");
  });

  it("finds the real agent outside the shim dir", () => {
    const home = tempDir("ficta-home-");
    const shimDir = defaultShimDir(home);
    const realBin = tempDir("ficta-real-bin-");
    executable(join(realBin, "claude"));

    const result = findExecutable("claude", {
      pathEnv: [shimDir, realBin].join(delimiter),
      excludeDirs: [shimDir],
    });

    expect(result).toBe(join(realBin, "claude"));
  });

  it("uninstalls only ficta-owned shims and removes the managed PATH block", () => {
    const home = tempDir("ficta-home-");
    const rcPath = join(home, ".zshrc");
    installShims({
      home,
      rcPath,
      updateShell: true,
      nodePath: "/usr/bin/node",
      fictaBin: "/repo/bin/ficta.mjs",
      agents: ["claude", "codex", "pi"],
    });

    const result = uninstallShims({ home, rcPath, agents: ["claude", "codex", "pi"] });

    expect(result.launcher.status).toBe("removed");
    expect(result.shims.map((s) => s.status)).toEqual(["removed", "removed", "removed"]);
    expect(result.pathBlockRemoved).toBe(true);
    expect(existsSync(join(defaultShimDir(home), ".ficta-launcher"))).toBe(false);
    expect(existsSync(join(defaultShimDir(home), "ficta"))).toBe(false);
    expect(existsSync(join(defaultShimDir(home), "claude"))).toBe(false);
    expect(readFileSync(rcPath, "utf8")).not.toContain("ficta shims");
  });
});
