import { randomBytes } from "node:crypto";
import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";

let loaded = false;

export function defaultConfigPath(): string {
  return join(homedir(), ".ficta", "config.env");
}

export function configPath(): string | undefined {
  const setting = process.env.FICTA_CONFIG_FILE;
  if (setting === "0") return undefined;
  return setting || defaultConfigPath();
}

/** Load ~/.ficta/config.env into process.env without overriding explicit env vars. */
export function loadUserConfig(): void {
  if (loaded) return;
  loaded = true;

  const path = configPath();
  if (!path || !existsSync(path)) return;

  for (const { key, value } of parseEnvFile(readFileSync(path, "utf8"))) {
    process.env[key] ??= value;
  }
}

export function writeUserConfig(values: Record<string, string>, path = defaultConfigPath()): void {
  ensurePrivateDir(dirname(path));
  writeFileSync(path, renderEnv(values), { mode: 0o600 });
  try {
    chmodSync(path, 0o600);
  } catch {
    // Best-effort on filesystems that do not support POSIX modes.
  }
}

/** Read an existing config file into a plain map (empty if missing). */
export function readUserConfig(path = defaultConfigPath()): Record<string, string> {
  if (!path || !existsSync(path)) return {};
  const out: Record<string, string> = {};
  for (const { key, value } of parseEnvFile(readFileSync(path, "utf8"))) out[key] = value;
  return out;
}

/**
 * Ensure a stable local surrogate key exists, so surrogates stay consistent across sessions.
 * No-op if one is already active (env or config file). Otherwise generates a 256-bit key, persists
 * it 0600 (merging with any existing config), and activates it for the current process. The key
 * never leaves the machine and is never printed.
 */
export function ensureSurrogateKey(path = configPath()): { generated: boolean; path?: string } {
  if (process.env.FICTA_SURROGATE_KEY) return { generated: false, path };
  if (!path) return { generated: false }; // config file disabled (FICTA_CONFIG_FILE=0)
  const values = readUserConfig(path);
  if (values.FICTA_SURROGATE_KEY) {
    process.env.FICTA_SURROGATE_KEY = values.FICTA_SURROGATE_KEY;
    return { generated: false, path };
  }
  const key = randomBytes(32).toString("hex");
  values.FICTA_SURROGATE_KEY = key;
  writeUserConfig(values, path);
  process.env.FICTA_SURROGATE_KEY = key;
  return { generated: true, path };
}

function ensurePrivateDir(path: string): void {
  mkdirSync(path, { recursive: true, mode: 0o700 });
  try {
    chmodSync(path, 0o700);
  } catch {
    // Best-effort on filesystems that do not support POSIX modes.
  }
}

function renderEnv(values: Record<string, string>): string {
  const lines = ["# Generated by `ficta setup`.", "# Shell environment variables override this file.", ""];
  for (const [key, value] of Object.entries(values)) lines.push(`${key}=${quoteEnvValue(value)}`);
  return `${lines.join("\n")}\n`;
}

function quoteEnvValue(value: string): string {
  if (/^[A-Za-z0-9_./:,@+=-]*$/.test(value)) return value;
  return JSON.stringify(value);
}

function parseEnvFile(text: string): Array<{ key: string; value: string }> {
  const out: Array<{ key: string; value: string }> = [];
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const match = line.match(/^(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/);
    if (!match) continue;
    const key = match[1] ?? "";
    const rawValue = (match[2] ?? "").trim();
    out.push({ key, value: parseEnvValue(rawValue) });
  }
  return out;
}

function parseEnvValue(raw: string): string {
  if (!raw) return "";
  const quote = raw[0];
  if ((quote === '"' || quote === "'") && raw.endsWith(quote)) {
    const inner = raw.slice(1, -1);
    return quote === '"' ? unescapeDoubleQuoted(inner) : inner;
  }
  return raw.replace(/\s+#.*$/, "").trim();
}

function unescapeDoubleQuoted(value: string): string {
  return value.replace(/\\(["\\nrt])/g, (_m, ch: string) => {
    switch (ch) {
      case "n":
        return "\n";
      case "r":
        return "\r";
      case "t":
        return "\t";
      default:
        return ch;
    }
  });
}
